"""add provider column to agents table

Revision ID: 41247760c39c
Revises: b27a5f15e296
Create Date: 2026-07-21 19:00:04.959128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41247760c39c'
down_revision: Union[str, Sequence[str], None] = 'b27a5f15e296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('provider', sa.Enum('openai', 'anthropic', 'gemini', 'ollama', 'groq', name='provider', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'provider')
    # ### end Alembic commands ###
